version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: "mysql://user:password@db:3306/mydb"
  #   depends_on:
  #     - db

volumes:
  db-data:
